ollama:
  model: "mistral:7b"
  timeout: 60
  stream: False
  address: "http://127.0.0.1:11434/api/generate"
  # system prompt you can change here 
  system: |
    Ты — быстрый голосовой ассистент.
    Отвечай максимально кратко и по делу.
    1–2 предложения.
    Без лишнего контекста.
    Без повторения вопроса.
    Без объяснений если их не просили.

    Ответ должен звучать естественно для озвучки.
piper_tts:
  voice: "ru_RU-irina-medium"
  num_channels: 1
  bits_per_sample: 2
  samplerate: 24000
whisper:
  model: base








