version: "3.9"

services:
  bot:
    build: ./bot
    secrets:
      - TOKEN
    environment:
      # путь к секрету в контейнере
      BOT_TOKEN_FILE: /run/secrets/TOKEN
    command: python bot.py

secrets:
  TOKEN:
    file: .env